remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Title and description
title: "AI for Cybersecurity Research Lunch"
description: "A Weekly Research Lunch at Texas A&M University"